name: ${project.artifactId}
version: ${project.version}
author: Rellynn
main: me.rellynn.foxmc.gameapiv2.GameAPIv2
depend: [FoxAPI]
commands:
  arena:
    description: Manage game arenas
  gamestart:
    description: Start the game
  leave:
    description: Leave the game